clone:
  git:
    image: plugins/git:next

pipeline:
  build:
    image: mhart/alpine-node
    environment:
      - PORT=8080
      - NODE_ENV=production
    commands:
      - cd app
      - apk --no-cache add tini \
          && addgroup -S node \
          && adduser -S -G node node
      - npm install
